name       : haste-it
version    : 1.0.6
release    : 3
source     :
    - git|https://github.com/DataDrake/haste-it : v1.0.6
license    : Apache-2.0
component  : network.clients
summary    : Simple little hastebin CLI tool written in Go
description: |
    Simple little hastebin CLI tool written in Go
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
    unlink $installdir/usr/bin/haste
