name       : haste-it
version    : 1.0.1
release    : 1
source     :
    - https://github.com/DataDrake/haste-it/archive/haste-it-1.0.1.tar.gz : 301dc14f6e3a7ca054aa3715093d2650bd383561d10918b14f9e689d4329ee14
license    : Apache-2.0
component  : network.clients
summary    : Simple little hastebin CLI tool written in Go
description: |
    Simple little hastebin CLI tool written in Go
builddeps  :
    - golang
build      : |
    %make
install    : |
    %make_install
    unlink $installdir/usr/bin/haste